<?php

namespace App\Http\Requests\User;

use Carbon\Carbon;
use Illuminate\Foundation\Http\FormRequest;

class ProfileRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'first_name' => 'required|string',
            'last_name' => 'required|string',
            'phone' => 'required|string|min:9|max:14',
            'birthday' => 'nullable|date|before:'.Carbon::parse(now())->format('d-m-Y'),
            'address' => 'required|string',
            'city' => 'required',
            'zipcode' => 'nullable|regex:/\b\d{5}\b/',
            'country' => 'required',

        ];
    }

    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
